/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.tout.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import com.rivetlogic.tout.model.ToutUserStatus;
import com.rivetlogic.tout.service.ToutUserStatusLocalService;
import com.rivetlogic.tout.service.persistence.ToutUserStatusPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the Tout Portlet Status by User local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.rivetlogic.tout.service.impl.ToutUserStatusLocalServiceImpl}.
 * </p>
 *
 * @author ronny.vargas
 * @see com.rivetlogic.tout.service.impl.ToutUserStatusLocalServiceImpl
 * @see com.rivetlogic.tout.service.ToutUserStatusLocalServiceUtil
 * @generated
 */
public abstract class ToutUserStatusLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ToutUserStatusLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.rivetlogic.tout.service.ToutUserStatusLocalServiceUtil} to access the Tout Portlet Status by User local service.
	 */

	/**
	 * Adds the Tout Portlet Status by User to the database. Also notifies the appropriate model listeners.
	 *
	 * @param toutUserStatus the Tout Portlet Status by User
	 * @return the Tout Portlet Status by User that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ToutUserStatus addToutUserStatus(ToutUserStatus toutUserStatus)
		throws SystemException {
		toutUserStatus.setNew(true);

		return toutUserStatusPersistence.update(toutUserStatus);
	}

	/**
	 * Creates a new Tout Portlet Status by User with the primary key. Does not add the Tout Portlet Status by User to the database.
	 *
	 * @param userId the primary key for the new Tout Portlet Status by User
	 * @return the new Tout Portlet Status by User
	 */
	@Override
	public ToutUserStatus createToutUserStatus(long userId) {
		return toutUserStatusPersistence.create(userId);
	}

	/**
	 * Deletes the Tout Portlet Status by User with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param userId the primary key of the Tout Portlet Status by User
	 * @return the Tout Portlet Status by User that was removed
	 * @throws PortalException if a Tout Portlet Status by User with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ToutUserStatus deleteToutUserStatus(long userId)
		throws PortalException, SystemException {
		return toutUserStatusPersistence.remove(userId);
	}

	/**
	 * Deletes the Tout Portlet Status by User from the database. Also notifies the appropriate model listeners.
	 *
	 * @param toutUserStatus the Tout Portlet Status by User
	 * @return the Tout Portlet Status by User that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ToutUserStatus deleteToutUserStatus(ToutUserStatus toutUserStatus)
		throws SystemException {
		return toutUserStatusPersistence.remove(toutUserStatus);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ToutUserStatus.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return toutUserStatusPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.tout.model.impl.ToutUserStatusModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return toutUserStatusPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.tout.model.impl.ToutUserStatusModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return toutUserStatusPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return toutUserStatusPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return toutUserStatusPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ToutUserStatus fetchToutUserStatus(long userId)
		throws SystemException {
		return toutUserStatusPersistence.fetchByPrimaryKey(userId);
	}

	/**
	 * Returns the Tout Portlet Status by User with the primary key.
	 *
	 * @param userId the primary key of the Tout Portlet Status by User
	 * @return the Tout Portlet Status by User
	 * @throws PortalException if a Tout Portlet Status by User with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public ToutUserStatus getToutUserStatus(long userId)
		throws PortalException, SystemException {
		return toutUserStatusPersistence.findByPrimaryKey(userId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return toutUserStatusPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the Tout Portlet Status by Users.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.rivetlogic.tout.model.impl.ToutUserStatusModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of Tout Portlet Status by Users
	 * @param end the upper bound of the range of Tout Portlet Status by Users (not inclusive)
	 * @return the range of Tout Portlet Status by Users
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<ToutUserStatus> getToutUserStatuses(int start, int end)
		throws SystemException {
		return toutUserStatusPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of Tout Portlet Status by Users.
	 *
	 * @return the number of Tout Portlet Status by Users
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getToutUserStatusesCount() throws SystemException {
		return toutUserStatusPersistence.countAll();
	}

	/**
	 * Updates the Tout Portlet Status by User in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param toutUserStatus the Tout Portlet Status by User
	 * @return the Tout Portlet Status by User that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ToutUserStatus updateToutUserStatus(ToutUserStatus toutUserStatus)
		throws SystemException {
		return toutUserStatusPersistence.update(toutUserStatus);
	}

	/**
	 * Returns the Tout Portlet Status by User local service.
	 *
	 * @return the Tout Portlet Status by User local service
	 */
	public com.rivetlogic.tout.service.ToutUserStatusLocalService getToutUserStatusLocalService() {
		return toutUserStatusLocalService;
	}

	/**
	 * Sets the Tout Portlet Status by User local service.
	 *
	 * @param toutUserStatusLocalService the Tout Portlet Status by User local service
	 */
	public void setToutUserStatusLocalService(
		com.rivetlogic.tout.service.ToutUserStatusLocalService toutUserStatusLocalService) {
		this.toutUserStatusLocalService = toutUserStatusLocalService;
	}

	/**
	 * Returns the Tout Portlet Status by User persistence.
	 *
	 * @return the Tout Portlet Status by User persistence
	 */
	public ToutUserStatusPersistence getToutUserStatusPersistence() {
		return toutUserStatusPersistence;
	}

	/**
	 * Sets the Tout Portlet Status by User persistence.
	 *
	 * @param toutUserStatusPersistence the Tout Portlet Status by User persistence
	 */
	public void setToutUserStatusPersistence(
		ToutUserStatusPersistence toutUserStatusPersistence) {
		this.toutUserStatusPersistence = toutUserStatusPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.rivetlogic.tout.model.ToutUserStatus",
			toutUserStatusLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.rivetlogic.tout.model.ToutUserStatus");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ToutUserStatus.class;
	}

	protected String getModelClassName() {
		return ToutUserStatus.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = toutUserStatusPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.rivetlogic.tout.service.ToutUserStatusLocalService.class)
	protected com.rivetlogic.tout.service.ToutUserStatusLocalService toutUserStatusLocalService;
	@BeanReference(type = ToutUserStatusPersistence.class)
	protected ToutUserStatusPersistence toutUserStatusPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ToutUserStatusLocalServiceClpInvoker _clpInvoker = new ToutUserStatusLocalServiceClpInvoker();
}